### PR TITLE
Adapt to 2.1.50+ backup mechanism

### LINKED ISSUE #166: Anki 2.1.50 throws exception on crowdanki imports on macOS Monterey 12.3.1 (AttributeError: 'AnkiQt' object has no attribute 'backup')
Importing a crowdanki document on Anki 2.1.50 (File > Crowd Anki Import from Disk) causes an exception to be thrown the import to fail. Failure occurs with my existing Anki Profile or with a new testing Anki Profile. It fails with a variety of crowdanki documents.

Upgrading the latest crowdanki via the Anki menu,

Downgrading to Anki 2.1.49 works around the error.

Here's the copied error:

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.50 (26d40c3a) Python 3.9.7 Qt 6.2.3 PyQt 6.2.3
Platform: Mac 12.3.1
Flags: frz=True ao=True sv=?
Add-ons, last update check: 2022-04-23 16:03:32
Add-ons possibly involved: ⁨CrowdAnki JSON exportimport Edit history Collaborate on deck creation⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/schwa/Library/Application Support/Anki2/addons21/1788670778/anki/ui/action_vendor.py", line 31, in <lambda>
    lambda: AnkiJsonImporter.import_deck(self.window.col, self.directory_vendor))
  File "/Users/schwa/Library/Application Support/Anki2/addons21/1788670778/importer/anki_importer.py", line 114, in import_deck
    AnkiJsonImporter.import_deck_from_path(collection, Path(directory_path))
  File "/Users/schwa/Library/Application Support/Anki2/addons21/1788670778/importer/anki_importer.py", line 103, in import_deck_from_path
    if importer.load_deck(directory_path):
  File "/Users/schwa/Library/Application Support/Anki2/addons21/1788670778/importer/anki_importer.py", line 37, in load_deck
    aqt.mw.backup()
AttributeError: 'AnkiQt' object has no attribute 'backup'
```

### PR DESCRIPTION
**Pull request by aplaice**
Fix #166.

It's no longer necessary for the collection to be closed before a backup, and AFAICT a closed collection can't even be backed up.

See PR 1728 in Anki itself.  (Not linking directly to avoid spam for DAE etc.)

This breaks compatibility with 2.1.49-.

Also: silence most verbose deprecation warnings (in 2.1.50+)

I've left the Qt warnings alone for now, since the behaviour varies between Qt5 and Qt6.

<hr/>

AFAICT importing, exporting and snapshotting all work in 2.1.50 and 2.1.52 both with Qt5 and Qt6 (using the default Qt5 compatibility shims).

### CODE REVIEW

**Comment by boydkelly** [comment]
> Fix #166.
> 
> It's no longer necessary for the collection to be closed before a backup, and AFAICT a closed collection can't even be backed up.
> 
> See PR 1728 in Anki itself. (Not linking directly to avoid spam for DAE etc.)
> 
> This breaks compatibility with 2.1.49-.
> 
> Also: silence most verbose deprecation warnings (in 2.1.50+)
> 
> I've left the Qt warnings alone for now, since the behaviour varies between Qt5 and Qt6.
> 
> AFAICT importing, exporting and snapshotting all work in 2.1.50 and 2.1.52 both with Qt5 and Qt6 (using the default Qt5 compatibility shims)al.

Tested also in 2.1.51 qt5 and 2.1.53 qt6   both imports successful.

Thank you very much!

**Comment by aplaice** [comment]
Thanks very much for testing (especially 2.1.53)! (I'll try to check if there are any other regressions there, soon-ish.)
